name: ironvault-auth-stack
version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ironvault_auth
      POSTGRES_USER: ironvault_auth
      POSTGRES_PASSWORD: ironvault_auth
    ports:
      - "5491:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - ironvault-auth-network

volumes:
  postgres_auth_data:

networks:
  ironvault-auth-network:
