spring:
  application:
    name: ironvault-auth

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5491/ironvault_auth}
    username: ${DB_USERNAME:ironvault_auth}
    password: ${DB_PASSWORD:ironvault_auth}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8081

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}
