spring:
  application:
    name: ironvault-auth

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      url: ${REDIS_URL}


server:
  port: ${PORT:8081}

app:
  internal:
    api-key: ${INTERNAL_API_KEY}
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}
  notifications:
    url: ${NOTIFICATIONS_URL}
    api-key: ${NOTIFICATIONS_API_KEY}
  auth:
    confirmation-url: ${AUTH_CONFIRMATION_URL}